version: '3.4'

services:
  main:
    build:
      context: ..
      dockerfile: ./Dockerfile
      network: host
    image: budva32
    expose:
      - '4004'
    volumes:
      - './:/app'
    working_dir: /app
    # stdin_open: true
    # tty: true
    ports:
      - 4004:4004
