version: "3.4"

services:
  telegram-forwarder:
    build:
      context: ..
      dockerfile: ./Dockerfile
      network: host
    image: telegram-forwarder
    container_name: telegram-forwarder
    hostname: telegram-forwarder
    expose:
      - "4004"
    volumes:
      - "./:/app"
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - 4004:4004
